#ifndef LVK_COMMON_VERSIONREV_H
#define LVK_COMMON_VERSIONREV_H

// DO NOT EDIT THIS FILE
// This file is automatically updated by bin/update-revision.sh

#define AUTO_APP_VERSION_REV     "4c3b2b97db83b0e605d4690000b42a2a22fd82ff"

#endif // LVK_COMMON_VERSIONREV_H
