#ifndef LVK_COMMON_VERSIONREV_H
#define LVK_COMMON_VERSIONREV_H

// DO NOT EDIT THIS FILE
// This file is automatically updated by bin/update-revision.sh

#define AUTO_APP_VERSION_REV     "76be5e12adccccf0366fe75c738a478cb29fedda"

#endif // LVK_COMMON_VERSIONREV_H
