#ifndef LVK_COMMON_VERSIONREV_H
#define LVK_COMMON_VERSIONREV_H

// DO NOT EDIT THIS FILE
// This file is automatically updated by bin/update-revision.sh

#define AUTO_APP_VERSION_REV     "c272414efde32d2b45304c4cecca87bb041b12d1"

#endif // LVK_COMMON_VERSIONREV_H
