@echo off

if exist c:\cygwin\bin\bash.exe (
    c:\cygwin\bin\bash.exe -l %1\sh\update-revision.sh
) else (
    echo ERROR bash not found. Git revision at common\versionrev.h cannot be updated. 1>&2
)

if not exist %1\common\versionrev.h (
    echo ERROR common\versionrev.h not found. Using default revision 0. 1>&2

    echo #ifndef LVK_COMMON_VERSIONREV_H > %1\common\versionrev.h
    echo #define LVK_COMMON_VERSIONREV_H >> %1\common\versionrev.h
    echo. >> %1\common\versionrev.h
    echo // DO NOT EDIT THIS FILE" >> %1\common\versionrev.h
    echo // This file is automatically generated by update-revision.bat >> %1\common\versionrev.h
    echo. >> %1\common\versionrev.h
    echo #define AUTO_APP_VERSION_REV     "0" >> %1\common\versionrev.h
    echo. >> %1\common\versionrev.h
    echo #endif // LVK_COMMON_VERSIONREV_H >> %1\common\versionrev.h
)
